### ISSUE TITLE
Look at adding POV displays to your code

### ISSUE THREAD

**Issue by tomjuggler** [marmilicious/FastLED_2_Processing#1]
Hi, first of all thanks for sharing your awesome code. I am finding it amazingly handy for testing my POV poi animations, with a few modifications, check out my fork of your code here: 

https://github.com/tomjuggler/FastLED_2_Processing/tree/POV_View 

I made a new branch to try out the POV display code. Included is an Arduino POV test sketch - it runs a bit slow with all the println() statements of course, but you can see the pictures without having to plug in LED's or swing anything! Also added a screenshot of it working on my system.

Best regards

tomjuggler

**Comment by marmilicious** [comment]
That's excellent Tom, thank you for sharing that.  Happy it was helpful!
-marc
